In [ ]:
#' Construct an index matrix identifying with which states each rate varies.
#' 
#' Called internally before rates are parsed when an epimodel object is 
#' initialized.
#' 
#' @inheritParams init_epimodel
#'   
#' @return binary index matrix indicating which changes in each compartment
#'   affect each rate
#' @export

init_rate_map <- function(rates, states) {
          
          # initialize matrix
          rate_map <- matrix(0, nrow = length(rates), ncol = length(states))
          colnames(rate_map) <- states
          
          # identify which states show up as arguments in each rate function
          for(t in 1:length(rates)) {
                    rate_map[t, sapply(states, grepl, rates[t])] <- 1
          }
          
          return(rate_map)
}

In [2]:
def init_rate_map(rates, states):
    
    import numpy as np
    
    rate_map = np.zeros((len(rates),len(states))).astype(int)
    
    for t in range(0,len(rates)):
        col_index = np.where(np.array(list(map(lambda x: (states[x] in rates[t])*1, range(len(states)))))==1)[0]
        rate_map[np.repeat(t,len(col_index)),col_index] =1
        
    rate_map.dtype = [(rates[0],'int'),(rates[1],'int'),(rates[2],'int')]
    
    return(rate_map)

In [3]:
import numpy as np

In [4]:
rates = ("beta*I", "mu", "gamma")
rates

('beta*I', 'mu', 'gamma')

In [5]:
states = ("S", "I", "R")
states

('S', 'I', 'R')

In [6]:
rate_map = np.zeros((len(rates),len(states))).astype(int)
rate_map

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
for t in range(0,len(rates)):
        col_index = np.where(np.array(list(map(lambda x: (states[x] in rates[t])*1, range(len(states)))))==1)[0]
        rate_map[np.repeat(t,len(col_index)),col_index] =1

In [8]:
rate_map

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
rate_map.shape

(3, 3)

In [10]:
rate_map.dtype = [(rates[0],'int'),(rates[1],'int'),(rates[2],'int')]
rate_map

array([[(0, 1, 0)],
       [(0, 0, 0)],
       [(0, 0, 0)]],
      dtype=[('beta*I', '<i8'), ('mu', '<i8'), ('gamma', '<i8')])

In [11]:
rate_map.shape 
# notice here that the dimension of rate_map change to (3,1)
# Ref: https://stackoverflow.com/questions/12362094/why-setting-dtype-on-numpy-array-changes-dimensions?rq=1

(3, 1)

In [12]:
rate_map['beta*I']

array([[0],
       [0],
       [0]])

In [13]:
rate_map['mu']

array([[1],
       [0],
       [0]])

In [14]:
rate_map['gamma']

array([[0],
       [0],
       [0]])